//APPICATION
#include "NVIC.h"
#include "EXTI.h"
#include "GPIO.h"
#include "RCC.h"

volatile uint8 u8GlobalFlag = 0;

int main(void){
	//SETTING RCC CLOCK AND ENABLING GPIOG PERIPHERAL
	vRCC_SetSYSCLK(PLL, HSE_RC, PLL_HSI, AHB_Pre1, APB1_Pre1, APB2_Pre1); // SET SYSCLK TO PLL AND SETTING PLL CLOCK TO HSI
	vRCC_EnPerClk(AHB1, GPIOG);
	//CONFIGURATION OF PIN13 AND OUTPUT OF HIGH ON PIN 13
	vGPIO_PinSetMode(GPIOG, PIN13, OUTPUT_MODE); // SETTING PIN TO OUTPUT MODE
	vGPIO_PinSetOutType(GPIOG, PIN13, OUTPUT_PUSH_PULL);  //SETTING OUTPUT MODE TO PUSH PULL MEANING OUTPUTS HIGH OR LOW
	vGPIO_PinSetOutSpeed(GPIOG, PIN13, LOW_SPEED); // SETTING SPEED OF SAID PIN TO LOW
	
	//CONFIGURATION OF PIN13 AND OUTPUT OF HIGH ON PIN 13
	vGPIO_PinSetMode(GPIOG, PIN14, OUTPUT_MODE); // SETTING PIN TO OUTPUT MODE
	vGPIO_PinSetOutType(GPIOG, PIN14, OUTPUT_PUSH_PULL); //SETTING OUTPUT MODE TO PUSH PULL MEANING OUTPUTS HIGH OR LOW
	vGPIO_PinSetOutSpeed(GPIOG, PIN14, LOW_SPEED);// SETTING SPEED OF SAID PIN TO LOW
	/* ENABLE INT FROM NVIC AND SET THE PENDING FLAG TO RAISE AN INTERRUPT */
	//EXTI0
	vNVIC_SetEnable(6);
	vNVIC_SetPending(6);
	
	while(1){
		if(u8GlobalFlag = 1){
			vGPIO_PinWrite(GPIOG, PIN13, TRUE); //TURN ON LED FOR PIN 13
			vGPIO_PinWrite(GPIOG, PIN14, TRUE); // TURN ON LED FOR PIN 14
			for(int i = 0; i < 500000; i++);
			vGPIO_PinWrite(GPIOG, PIN13, FALSE); //TURN OFF LED FOR PIN 13
			vGPIO_PinWrite(GPIOG, PIN14, FALSE); // TURN OFF LED FOR PIN 14
			for(int i = 0; i < 500000; i++);
			u8GlobalFlag = 0;
		}
	}
}

void EXTI0_IRQHandler(void){
	u8GlobalFlag = 1;
}
